-- MySQL Script generated by MySQL Workbench
-- 02/22/16 15:16:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TresMuseos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TresMuseos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TresMuseos` ;
USE `TresMuseos` ;

-- -----------------------------------------------------
-- Table `TresMuseos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TresMuseos`.`Usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `score` INT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TresMuseos`.`Museo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TresMuseos`.`Museo` (
  `idmuseo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `imgURL` VARCHAR(45) NULL,
  PRIMARY KEY (`idmuseo`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TresMuseos`.`Exposicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TresMuseos`.`Exposicion` (
  `idexposicion` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `imgURL` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  `idmuseo` INT NOT NULL,
  PRIMARY KEY (`idexposicion`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `idmuseo_idx` (`idmuseo` ASC),
  CONSTRAINT `idmuseo`
    FOREIGN KEY (`idmuseo`)
    REFERENCES `TresMuseos`.`Museo` (`idmuseo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TresMuseos`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TresMuseos`.`Sala` (
  `idsala` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `mapImgURL` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  `idexposicion` INT NOT NULL,
  PRIMARY KEY (`idsala`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `idexposicion_idx` (`idexposicion` ASC),
  CONSTRAINT `idexposicion`
    FOREIGN KEY (`idexposicion`)
    REFERENCES `TresMuseos`.`Exposicion` (`idexposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TresMuseos`.`OptionPregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TresMuseos`.`OptionPregunta` (
  `idoption` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `imgURL` VARCHAR(45) NULL,
  `idpregunta` INT NOT NULL,
  PRIMARY KEY (`idoption`),
  INDEX `idpregunta_idx` (`idpregunta` ASC),
  CONSTRAINT `idpregunta`
    FOREIGN KEY (`idpregunta`)
    REFERENCES `TresMuseos`.`Pregunta` (`idpregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TresMuseos`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TresMuseos`.`Pregunta` (
  `idpregunta` INT NOT NULL AUTO_INCREMENT,
  `extraInfo` VARCHAR(200) NOT NULL,
  `imgURL` VARCHAR(45) NULL,
  `idsala` INT NOT NULL,
  `active` TINYINT(1) NULL,
  `idanswer` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpregunta`),
  INDEX `idsala_idx` (`idsala` ASC),
  INDEX `idanswer_idx` (`idanswer` ASC),
  CONSTRAINT `idsala`
    FOREIGN KEY (`idsala`)
    REFERENCES `TresMuseos`.`Sala` (`idsala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idanswer`
    FOREIGN KEY (`idanswer`)
    REFERENCES `TresMuseos`.`OptionPregunta` (`idoption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
